# Generated by Django 6.0.6 on 2026-10-02 20:17

import django.db.models.deletion
import django.utils.timezone
import homework.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0002_sessionfile'),
        ('students', '0003_student_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('SCORED', 'Scored')], db_index=True, default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to=settings.AUTH_USER_MODEL)),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_homework', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='sessions_app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.student')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'db_table': 'homework',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='submission', max_length=20)),
                ('file', models.FileField(max_length=512, upload_to=homework.models.homework_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.homework')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_homework_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework File',
                'verbose_name_plural': 'Homework Files',
                'db_table': 'homework_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['student', 'status'], name='homework_student_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_score__gt', 0), ('max_score__isnull', False), ('score__gte', 0), ('score__isnull', False), ('score__lte', models.F('max_score')), ('status', 'SCORED')), models.Q(models.Q(('status', 'SCORED'), _negated=True), ('max_score__isnull', True), ('score__isnull', True)), _connector='OR'), name='homework_score_valid'),
        ),
    ]
