# Generated by Django 6.0.6 on 2026-10-02 06:44

import django.db.models.deletion
import django.utils.timezone
import exams.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('SCORED', 'Scored')], db_index=True, default='ASSIGNED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_additional_exams', to=settings.AUTH_USER_MODEL)),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_additional_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_exams', to='students.student')),
            ],
            options={
                'verbose_name': 'Additional Exam',
                'verbose_name_plural': 'Additional Exams',
                'db_table': 'additional_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalExamFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('question_paper', 'Question paper'), ('answer_sheet', 'Answer sheet')], max_length=20)),
                ('file', models.FileField(max_length=512, upload_to=exams.models.additional_exam_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('additional_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.additionalexam')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_additional_exam_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional Exam File',
                'verbose_name_plural': 'Additional Exam Files',
                'db_table': 'additional_exam_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CHAPTER', 'Chapter')], default='CHAPTER', max_length=20)),
                ('chapter_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('recording_link', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('question_paper', 'Question paper'), ('answer_sheet', 'Answer sheet')], default='question_paper', max_length=20)),
                ('file', models.FileField(max_length=512, upload_to=exams.models.exam_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.exam')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exam_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam File',
                'verbose_name_plural': 'Exam Files',
                'db_table': 'exam_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='additionalexam',
            index=models.Index(fields=['student', 'status'], name='add_exams_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalexam',
            index=models.Index(fields=['mentor', 'status'], name='add_exams_mentor_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='additionalexam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_score__gt', 0), ('max_score__isnull', False), ('score__gte', 0), ('score__isnull', False), ('score__lte', models.F('max_score')), ('status', 'SCORED')), models.Q(models.Q(('status', 'SCORED'), _negated=True), ('max_score__isnull', True), ('score__isnull', True)), _connector='OR'), name='additional_exams_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='additionalexamfile',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['question_paper', 'answer_sheet'])), name='additional_exam_files_kind_valid'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['student', 'status'], name='exams_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['mentor', 'status'], name='exams_mentor_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exams_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_score__gt', 0), ('max_score__isnull', False), ('score__gte', 0), ('score__isnull', False), ('score__lte', models.F('max_score')), ('status', 'ATTENDED')), models.Q(models.Q(('status', 'ATTENDED'), _negated=True), ('max_score__isnull', True), ('score__isnull', True)), _connector='OR'), name='exams_score_valid'),
        ),
    ]
