# Generated by Django 6.0.6 on 2026-09-28 22:42

import django.db.models.deletion
import django.utils.timezone
import sessions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('notes', 'Notes'), ('recording', 'Recording'), ('homework', 'Homework')], max_length=20)),
                ('file', models.FileField(max_length=512, upload_to=sessions.models.session_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sessions_app.session')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_session_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session File',
                'verbose_name_plural': 'Session Files',
                'db_table': 'session_files',
                'constraints': [models.UniqueConstraint(fields=('session', 'field'), name='session_files_one_per_field')],
            },
        ),
    ]
